// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-rmF6rmsquJCGaBK1oLFReoHMzBAgMKM',
    appId: '1:242017278548:web:fdab4f8be7e32eb90e6bc1',
    messagingSenderId: '242017278548',
    projectId: 'dht11-68fae',
    authDomain: 'dht11-68fae.firebaseapp.com',
    databaseURL: 'https://dht11-68fae-default-rtdb.firebaseio.com',
    storageBucket: 'dht11-68fae.appspot.com',
    measurementId: 'G-6JJQ262G2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1h7mxfN-l1KlLeeEwHoYuSt3-NA4G28Y',
    appId: '1:242017278548:android:5a3ba1976b366ca00e6bc1',
    messagingSenderId: '242017278548',
    projectId: 'dht11-68fae',
    databaseURL: 'https://dht11-68fae-default-rtdb.firebaseio.com',
    storageBucket: 'dht11-68fae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiTnWG1ZgsQtkE7v_b7wjJ6qOiWTi7Uzc',
    appId: '1:242017278548:ios:f064b21669ad84cf0e6bc1',
    messagingSenderId: '242017278548',
    projectId: 'dht11-68fae',
    databaseURL: 'https://dht11-68fae-default-rtdb.firebaseio.com',
    storageBucket: 'dht11-68fae.appspot.com',
    iosBundleId: 'com.example.doan1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiTnWG1ZgsQtkE7v_b7wjJ6qOiWTi7Uzc',
    appId: '1:242017278548:ios:742619ed8f0661a60e6bc1',
    messagingSenderId: '242017278548',
    projectId: 'dht11-68fae',
    databaseURL: 'https://dht11-68fae-default-rtdb.firebaseio.com',
    storageBucket: 'dht11-68fae.appspot.com',
    iosBundleId: 'com.example.doan1.RunnerTests',
  );
}
